### ISSUE TITLE
활동

### ISSUE THREAD

**Issue by limehee** [kgu-clab/clab-platforms-server#131]
### Describe

동아리 내에서 이루어지는 스터디, 프로젝트 등의 활동을 보다 쉽게 추적하고 관리할 수 있도록 합니다.

### Tasks

- [x] 스터디 그룹(멤버 관리/일정/과제 제출 및 피드백)
- [x] 프로젝트 그룹(멤버 관리/활동 보고서 제출)
- [x] 공동 신청 양식 폼
- [x] 활동 보고서 관리 테이블 분리
- [x] 주차별 활동 보고서 관리
