### ISSUE TITLE
ActivityGroupMember 신청폼 관련 api 수정 및 추가, ActivityGroup 예외처리 수정

### ISSUE THREAD

**Issue by mingmingmon** [kgu-clab/clab-platforms-server#189]
### Describe

활동 그룹에 신청하기 화면에서 필요한 api를 추가하고 필요없는 전달사항을 제외합니다.

### Tasks

- [x] 신청폼에 고정으로 들어갈 정보 반환하는 api 추가 (로그인한 멤버 기준으로 학번, 이름, 학과, 학년)
- [x] 그룹 리더가 지원자의 신청폼을 조회할 수 있는 api 추가 
- [x] 신청폼 requestDto에 필요없는 내용 제거 (1번 task의 내용 삭제 예정)
