### ISSUE TITLE
ActivityGroupBoard 관련 api 수정 및 추가

### ISSUE THREAD

**Issue by mingmingmon** [kgu-clab/clab-platforms-server#190]
### Describe

활동 그룹의 일정관리, 공지사항, 과제제출 등을 위해 ActivityGroupBoard에 있는 api를 사용하려 합니다.
이에 필요하거나 수정되어야 하는 api를 작업합니다.

### Tasks

- [ ] 활동 그룹 게시글 생성 시 종료 일시(마감 일자)를 입력할 수 있게 함 (이는 주로 과제 제출 관련 게시글에 쓰일 것이고 따라서 필수값은 아님)
- [ ] 활동 그룹 게시글 조회 시 응답 dto에 파일 서버 보관 기간 추가
- [ ] 부모 게시글 id에 대한 자식 게시글 하나만 반환하는 api 추가
- [ ] 활동 그룹 게시글 requestDto에 notnull 모두 제거
