### ISSUE TITLE
ActivityGroupBoard 카테고리 수정과 api 수정

### ISSUE THREAD

**Issue by mingmingmon** [kgu-clab/clab-platforms-server#213]
### Describe

활동 그룹 게시판 카테고리 수정과 필요없는 api를 삭제하고 필요한 api를 추가합니다.

### Tasks

- [x] 제출 게시판에 대한 피드백 게시판 불러오기
- [x] isAssignmnetBoard 칼럼 삭제하고 카테고리로 처리하기
- [x] ASSIGNMENT "과제", SUBMIT "제출"로 카테고리 enum 수정
- [x] responseDto에 createdAt 넣어주기
- [x] 게시판 생성 시 responseDto에 넣을 값 설명 description에 설명
