### ISSUE TITLE
활동 그룹 멤버 관리 시스템 개선

### ISSUE THREAD

**Issue by limehee** [kgu-clab/clab-platforms-server#219]
### Describe

현재 그룹 멤버와 관련한 다양한 API를 제공하고 있지만, 기획이 중간에 수정됨에 따라 누락된 API가 발견되었습니다.
초기 기획안을 따라 활동 그룹 리더가 신청 멤버를 수락/거절할 수 있도록 하기 위해 다음의 API를 새로 개발하고 개선합니다.

### Tasks

- [x] 그룹멤버 조회했을때 상태도 같이 반환
- [x] 상태 개선(진행중->승인대기)
- [x] 상태별로 그룹멤버 조회하는 API 추가
- [x] 활동 신청 / 지원 폼으로 신청 API 병합
- [x] 활동 그룹 승인이 이루어진 멤버만 출석체크 등의 작업에 포함되도록 변경
