### ISSUE TITLE
파일 업로드와 활동 게시판 수정일시 리팩토링

### ISSUE THREAD

**Issue by mingmingmon** [kgu-clab/clab-platforms-server#238]
### Describe

과제 파일 업로드 요청 시 로그인 한 유저를 파라미터로 받지 않고 jwt로 처리하도록 합니다.
활동게시판에서 수정한 일시도 dto에 담아서 반환하도록 합니다.

### Tasks

- [x] 과제 파일 업로드 로그인한 유저 부분  jwt로 처리하기
- [x] 활동 게시판 수정 일시 dto에 담기
- [x] 파일 삭제 시 (자동삭제 + 생성 전 이전 것 삭제 + 파일삭제 api를 통한 삭제) 파일 자체만 삭제하고 DB의 파일 정보는 놔두기
- [x] 프로필과 클라우드 파일 api 로그인한 유저 부분 jwt 처리
