### ISSUE TITLE
Swagger UI 접근 제어

### ISSUE THREAD

**Issue by limehee** [kgu-clab/clab-platforms-server#249]
### Describe

[1]
현재 Swagger UI에 대한 접근을 로그인을 통해 제어하고 있습니다.
하지만 Basic Auth 방식의 특성상 암호화를 하지않고 Base64로 인코딩하여 ID와 PW를 전달하며, 보안상 매우 취약합니다.
따라서 화이트리스트 IP를 별도의 파일로 보관하여 접근이 허용된 IP만 Swagger UI에 접근할 수 있도록 합니다.

[2]
Swagger UI Path를 별도 지정하여 리다이렉션하도록 합니다.
리다이렉션을 통해 접근한 경우에만 Swagger UI에 접속이 가능하며, 직접 URL에 접근할 경우 접속을 차단합니다.

### Tasks

- [x] yml을 통한 화이트리스트 접근 정보 관리
- [x] 정보 저장 규칙 설정
- [x] Swagger UI 접근 제어 설정
- [x] Swagger UI Custom Path 지정
- [x] Swagger UI 접근 정보 숨김
