### ISSUE TITLE
보안 설정 관심사 분리 및 SRP 준수

### ISSUE THREAD

**Issue by limehee** [kgu-clab/clab-platforms-server#252]
### Describe

시스템의 규모가 커짐에 따라 보안 설정이 늘어나고, 그 결과 SecurityConfig 및 Filter의 코드 복잡성이 올라갔습니다.
유지보수 및 가독성 향상을 위해 보안과 관련한 설정에 대해 관심사를 분리하고 단일 책임 원칙(SRP)을 준수할 수 있도록 합니다.

### Tasks

- [x] SecurityConfig에 집중되어 있는 설정을 카테고리별로 분리
- [x] SecurityConfig filterChain 모듈화
- [x] 하나의 메서드로 작성되어 있는 Filter 코드 모듈화
- [x] Whitelist 로직 Service 분리
- [x] Swagger 관련 코드 분리
- [x] 오류에 대한 응답 처리 중앙화
