### ISSUE TITLE
공동 계정 개선

### ISSUE THREAD

**Issue by limehee** [kgu-clab/clab-platforms-server#255]
### Describe

[1]
공동 계정 이용을 신청하는 즉시 계정 상태가 사용 중으로 바뀌도록 설계되어있습니다.
이용 신청을 할 때 이용 시작 시간을 같이 정보로 전달하기 때문에, 시작 시간을 고려하여 사용 중으로 변경해야 합니다.

[2]
공동 계정 이용 신청 취소 API와 공동 계정 이용 완료 API의 행위적 특성이 중복됩니다.
두 API를 통합하여 하나의 API에서 신청 취소 및 이용 완료가 이뤄질 수 있도록 합니다.

### Tasks

- [x] 공동 계정을 사용 중이지 않음에도 사용 중으로 표시되는 문제 수정
- [x] 공동 계정 이용 취소/완료 API 통합
- [x] 예약 기능 추가
- [x] 스케줄링 성능 개선
