### ISSUE TITLE
활동 그룹 게시판 개선

### ISSUE THREAD

**Issue by limehee** [kgu-clab/clab-platforms-server#260]
### Describe

[1]
활동 그룹 게시판을 조작하는 과정에서 발생하는 예외를 개선합니다.

[2]
클라이언트에서 과제 파일 업로드 실패를 탐지하고 게시판 수정시 부모 게시판의 ID를 알 수 있게 합니다.

### Tasks

- [x] 활동 그룹 게시판 카테고리를 수정할 수 없도록 변경
- [x] 활동 그룹 게시판 수정시 부모 게시판 ID를 같이 반환하도록 변경
- [x] 과제 파일 업로드 실패시 반환되는 정보 변경
