### ISSUE TITLE
활동관련 2차 QA에 따른 활동 게시판 로직 수정

### ISSUE THREAD

**Issue by mingmingmon** [kgu-clab/clab-platforms-server#530]
### Describe

활동 2차 QA 후 조율이 완료된 부분을 반영하고, 잘못된 로직을 수정하고자 합니다.

### Tasks
- [x] 과제 제출 시 파일이나 설명 둘 중 하나만 입력해도 제출 가능하게 수정
-> 서버 로직에서는 파일과 설명에 대한 필수제약을 걸지 않았으므로 프론트에게 확인 요청했습니다.
- [x] 활동 생성 시 내용과 커리큘럼 글자 수 제한 1000자로 변경
- [x] 활동에 참여하지 않은 멤버는 공지, 주차별 활동, 과제의 상세조회를 할 수 없도록 수정
-> 프론트에서 파일을 보여주지 않는 것으로 처리되었습니다.
