### ISSUE TITLE
활동 관련 2차 QA에 따른 활동 멤버 관련 로직 수정

### ISSUE THREAD

**Issue by mingmingmon** [kgu-clab/clab-platforms-server#532]
### Describe

활동 2차 QA 후 활동 멤버 관련 로직을 수정하고 필요한 API를 추가하도록 합니다.

### Tasks
- [ ] 활동 멤버 직책 수정 시 리더가 1명 남은 경우 멤버로 변경할 수 없도록 제약
- [ ] 활동 그룹 참여자 정렬을 ACCEPTED, WAITING, REJECT 순으로 수정
- [ ] 스터디 삭제 권한을 super, admin, leader로 수정
