### ISSUE TITLE
활동 관련 2차 QA에 따른 활동 관리 로직 수정

### ISSUE THREAD

**Issue by mingmingmon** [kgu-clab/clab-platforms-server#533]
### Describe

2차 QA 이후 활동 관리 로직에서 수정하거나 필요한 부분을 추가하고자 합니다.

### Tasks

- [x] 활동 신청 멤버를 일괄 승인 할 수 있는 API 추가
- [x] 스터디 종료 일자 후에 자동으로 상태를 END로 변경할 수 있도록 수정
- [x] 활동 상태별 조회 시 페이징 미적용 문제 확인
