### ISSUE TITLE
게시글 이모지, 댓글 좋아요 토글의 삭제 방식에 따른 성능 개선

### ISSUE THREAD

**Issue by mingmingmon** [kgu-clab/clab-platforms-server#634]
### Describe

#633 을 진행하면서 게시글 이모지에는 소프트 딜리트가 적용되고, 댓글 좋아요에는 하드 딜리트가 적용되고 있음을 확인했습니다.

비슷한 로직임에도 삭제 정책이 일관되지 않아, 성능적으로 효율적인 방식을 확인하고 통일하고자 합니다.

### Tasks

- [ ] 소프트 딜리트 시 토글 성능 측정
- [ ] 하드 딜리트 시 토글 성능 측정
- [ ] 최적 방식으로 수정
