### ISSUE TITLE
운영진 관리 기능 구현

### ISSUE THREAD

**Issue by SongJaeHoonn** [kgu-clab/clab-platforms-server#642]
### Describe

**C-Lab 운영진 정보들을 등록, 변경, 조회, 삭제할 수 있는 기능을 구현하려고 합니다.**

**기존에 백엔드를 거치지 않고 프론트엔드에서 하드코딩 되어있던 기존의 구조에는 문제점이 있습니다.**

1. 운영진 정보를 추가하거나, 변경될 때마다 프론트엔드 코드를 수정해야 합니다.
2. 실수로 정보를 잘못 넣었을 때 다시 수정해 배포하는 작업이 오래 걸릴 수 있습니다.
3. 운영진에 대해 관리할 요소가 늘어나고 복잡해진다면, 프론트에서만 처리하기 어렵다는 확장성의 문제가 발생합니다.
4. 민감한 정보가 클라이언트 코드에 그대로 노출되어 보안의 문제도 발생합니다.

따라서, 운영진의 정보를 DB에 저장하여 관리하고자 합니다.
관리할 정보는 다음과 같습니다.
- **사진, 이름, 분야, 이메일, 직급, 학번**

---

### Tasks

- [ ] 운영진 등록 기능 구현
- [ ] 운영진 변경 기능 구현
- [ ] 운영진 조회 기능 구현
- [ ] 운영진 삭제 기능 구현
